export const queries = [
  {
    id: 1,
    query: "SELECT * FROM employees;",
    data: [
      {
        employeeID: 1,
        lastName: "Davolio",
        firstName: "Nancy",
        title: "Sales Representative",
        birthDate: "1948-12-08 00:00:00.000",
        hireDate: "1992-05-01 00:00:00.000",
        address: "507 20th Ave. E. Apt. 2A",
        city: "Seattle",
        region: "WA",
        postalCode: 98122,
        country: "USA",
        homePhone: "(206) 555-9857",
        extension: 5467,
        photoPath: "http://accweb/emmployees/davolio.bmp",
        notes: "Education includes a BA in psychology...",
        reportsTo: 2,
      },
      {
        employeeID: 1,
        lastName: "Davolio",
        firstName: "Nancy",
        title: "Sales Representative",
        birthDate: "1948-12-08 00:00:00.000",
        hireDate: "1992-05-01 00:00:00.000",
        address: "507 20th Ave. E. Apt. 2A",
        city: "Seattle",
        region: "WA",
        postalCode: 98122,
        country: "USA",
        homePhone: "(206) 555-9857",
        extension: 5467,
        photoPath: "http://accweb/emmployees/davolio.bmp",
        notes: "Education includes a BA in psychology...",
        reportsTo: 2,
      },
      {
        employeeID: 1,
        lastName: "Davolio",
        firstName: "Nancy",
        title: "Sales Representative",
        birthDate: "1948-12-08 00:00:00.000",
        hireDate: "1992-05-01 00:00:00.000",
        address: "507 20th Ave. E. Apt. 2A",
        city: "Seattle",
        region: "WA",
        postalCode: 98122,
        country: "USA",
        homePhone: "(206) 555-9857",
        extension: 5467,
        photoPath: "http://accweb/emmployees/davolio.bmp",
        notes: "Education includes a BA in psychology...",
        reportsTo: 2,
      },
      {
        employeeID: 1,
        lastName: "Davolio",
        firstName: "Nancy",
        title: "Sales Representative",
        birthDate: "1948-12-08 00:00:00.000",
        hireDate: "1992-05-01 00:00:00.000",
        address: "507 20th Ave. E. Apt. 2A",
        city: "Seattle",
        region: "WA",
        postalCode: 98122,
        country: "USA",
        homePhone: "(206) 555-9857",
        extension: 5467,
        photoPath: "http://accweb/emmployees/davolio.bmp",
        notes: "Education includes a BA in psychology...",
        reportsTo: 2,
      },
      {
        employeeID: 2,
        lastName: "Davolio",
        firstName: "Nancy",
        title: "Sales Representative",
        birthDate: "1948-12-08 00:00:00.000",
        hireDate: "1992-05-01 00:00:00.000",
        address: "507 20th Ave. E. Apt. 2A",
        city: "Seattle",
        region: "WA",
        postalCode: 98122,
        country: "USA",
        homePhone: "(206) 555-9857",
        extension: 5467,
        photoPath: "http://accweb/emmployees/davolio.bmp",
        notes: "Education includes a BA in psychology...",
        reportsTo: 2,
      },
    ],
  },
  {
    id: 2,
    query: "SELECT * FROM salaries;",
    data: [
      { Department: "Engineering", avg_salary: 95000 },
      { Department: "Marketing", avg_salary: 65000 },
      { Department: "HR", avg_salary: 55000 },
      { Department: "Finance", avg_salary: 75000 },
    ],
  },
  {
    "id": 3,
    "query": "SELECT month",
    "data": [
      { "Month": "January", "Total_Sales": 50000 },
      { "Month": "February", "Total_Sales": 42000 },
      { "Month": "March", "Total_Sales": 62000 },
      { "Month": "April", "Total_Sales": 70000 },
      { "Month": "May", "Total_Sales": 75000 },
      { "Month": "June", "Total_Sales": 68000 },
      { "Month": "July", "Total_Sales": 72000 },
      { "Month": "August", "Total_Sales": 69000 },
      { "Month": "September", "Total_Sales": 71000 },
      { "Month": "October", "Total_Sales": 73000 },
      { "Month": "November", "Total_Sales": 77000 },
      { "Month": "December", "Total_Sales": 80000 }
    ]
  },
  {
    "id": 5,
    "query": "SELECT category",
    "data": [
      { "Category": "Electronics", "Avg_Rating": 4.5 },
      { "Category": "Clothing", "Avg_Rating": 3.9 },
      { "Category": "Home Appliances", "Avg_Rating": 4.2 },
      { "Category": "Books", "Avg_Rating": 4.8 },
      { "Category": "Toys & Games", "Avg_Rating": 4.3 },
      { "Category": "Beauty & Personal Care", "Avg_Rating": 4.6 },
      { "Category": "Automotive", "Avg_Rating": 3.7 },
      { "Category": "Furniture", "Avg_Rating": 4.1 },
      { "Category": "Sports & Outdoors", "Avg_Rating": 4.4 },
      { "Category": "Groceries", "Avg_Rating": 4.0 }
    ]
  }
  
  
  
];
