export const queries = [
  {
    id: 1,
    query: "SELECT * FROM employees;",
    data: [
      {
        employeeID: 1,
        lastName: "Davolio",
        firstName: "Nancy",
        title: "Sales Representative",
        birthDate: "1948-12-08 00:00:00.000",
        hireDate: "1992-05-01 00:00:00.000",
        address: "507 20th Ave. E. Apt. 2A",
        city: "Seattle",
        region: "WA",
        postalCode: 98122,
        country: "USA",
        homePhone: "(206) 555-9857",
        extension: 5467,
        photoPath: "http://accweb/emmployees/davolio.bmp",
        notes: "Education includes a BA in psychology...",
        reportsTo: 2,
      },
      {
        employeeID: 1,
        lastName: "Davolio",
        firstName: "Nancy",
        title: "Sales Representative",
        birthDate: "1948-12-08 00:00:00.000",
        hireDate: "1992-05-01 00:00:00.000",
        address: "507 20th Ave. E. Apt. 2A",
        city: "Seattle",
        region: "WA",
        postalCode: 98122,
        country: "USA",
        homePhone: "(206) 555-9857",
        extension: 5467,
        photoPath: "http://accweb/emmployees/davolio.bmp",
        notes: "Education includes a BA in psychology...",
        reportsTo: 2,
      },
      {
        employeeID: 1,
        lastName: "Davolio",
        firstName: "Nancy",
        title: "Sales Representative",
        birthDate: "1948-12-08 00:00:00.000",
        hireDate: "1992-05-01 00:00:00.000",
        address: "507 20th Ave. E. Apt. 2A",
        city: "Seattle",
        region: "WA",
        postalCode: 98122,
        country: "USA",
        homePhone: "(206) 555-9857",
        extension: 5467,
        photoPath: "http://accweb/emmployees/davolio.bmp",
        notes: "Education includes a BA in psychology...",
        reportsTo: 2,
      },
      {
        employeeID: 1,
        lastName: "Davolio",
        firstName: "Nancy",
        title: "Sales Representative",
        birthDate: "1948-12-08 00:00:00.000",
        hireDate: "1992-05-01 00:00:00.000",
        address: "507 20th Ave. E. Apt. 2A",
        city: "Seattle",
        region: "WA",
        postalCode: 98122,
        country: "USA",
        homePhone: "(206) 555-9857",
        extension: 5467,
        photoPath: "http://accweb/emmployees/davolio.bmp",
        notes: "Education includes a BA in psychology...",
        reportsTo: 2,
      },
      {
        employeeID: 2,
        lastName: "Davolio",
        firstName: "Nancy",
        title: "Sales Representative",
        birthDate: "1948-12-08 00:00:00.000",
        hireDate: "1992-05-01 00:00:00.000",
        address: "507 20th Ave. E. Apt. 2A",
        city: "Seattle",
        region: "WA",
        postalCode: 98122,
        country: "USA",
        homePhone: "(206) 555-9857",
        extension: 5467,
        photoPath: "http://accweb/emmployees/davolio.bmp",
        notes: "Education includes a BA in psychology...",
        reportsTo: 2,
      },
    ],
  },
  {
    id: 2,
    query: "SELECT * FROM salaries;",
    data: [
      { Department: "Engineering", avg_salary: 95000 },
      { Department: "Marketing", avg_salary: 65000 },
      { Department: "HR", avg_salary: 55000 },
      { Department: "Finance", avg_salary: 75000 },
    ],
  },
  {
    id: 3,
    query: "SELECT month",
    data: [
      { Month: "January", Total_Sales: 50000 },
      { Month: "February", Total_Sales: 42000 },
      { Month: "March", Total_Sales: 62000 },
      { Month: "April", Total_Sales: 70000 },
      { Month: "May", Total_Sales: 75000 },
      { Month: "June", Total_Sales: 68000 },
      { Month: "July", Total_Sales: 72000 },
      { Month: "August", Total_Sales: 69000 },
      { Month: "September", Total_Sales: 71000 },
      { Month: "October", Total_Sales: 73000 },
      { Month: "November", Total_Sales: 77000 },
      { Month: "December", Total_Sales: 80000 },
    ],
  },
  {
    id: 5,
    query: "SELECT category",
    data: [
      { Category: "Electronics", Avg_Rating: 4.5 },
      { Category: "Clothing", Avg_Rating: 3.9 },
      { Category: "Home Appliances", Avg_Rating: 4.2 },
      { Category: "Books", Avg_Rating: 4.8 },
      { Category: "Toys & Games", Avg_Rating: 4.3 },
      { Category: "Beauty & Personal Care", Avg_Rating: 4.6 },
      { Category: "Automotive", Avg_Rating: 3.7 },
      { Category: "Furniture", Avg_Rating: 4.1 },
      { Category: "Sports & Outdoors", Avg_Rating: 4.4 },
      { Category: "Groceries", Avg_Rating: 4.0 },
    ],
  },
  {
    id: 5,
    query: "SELECT company",
    data: [
      {
        Employee: "Amit Sharma",
        Age: 32,
        Department: "Sales",
        Experience: 8,
        PerformanceScore: 85,
        Salary: 720000,
      },
      {
        Employee: "Neha Verma",
        Age: 29,
        Department: "Marketing",
        Experience: 6,
        PerformanceScore: 78,
        Salary: 650000,
      },
      {
        Employee: "Rajesh Gupta",
        Age: 35,
        Department: "HR",
        Experience: 10,
        PerformanceScore: 90,
        Salary: 750000,
      },
      {
        Employee: "Pooja Reddy",
        Age: 28,
        Department: "IT",
        Experience: 5,
        PerformanceScore: 88,
        Salary: 810000,
      },
      {
        Employee: "Vikram Choudhary",
        Age: 40,
        Department: "Finance",
        Experience: 15,
        PerformanceScore: 92,
        Salary: 960000,
      },
      {
        Employee: "Sonia Kapoor",
        Age: 31,
        Department: "Sales",
        Experience: 7,
        PerformanceScore: 80,
        Salary: 700000,
      },
      {
        Employee: "Arjun Mehta",
        Age: 33,
        Department: "IT",
        Experience: 9,
        PerformanceScore: 85,
        Salary: 820000,
      },
      {
        Employee: "Meera Joshi",
        Age: 27,
        Department: "Marketing",
        Experience: 4,
        PerformanceScore: 75,
        Salary: 620000,
      },
      {
        Employee: "Kunal Saxena",
        Age: 38,
        Department: "HR",
        Experience: 13,
        PerformanceScore: 89,
        Salary: 880000,
      },
      {
        Employee: "Riya Malhotra",
        Age: 30,
        Department: "Finance",
        Experience: 8,
        PerformanceScore: 91,
        Salary: 940000,
      },
    ],
  },
  {
    id: 5,
    query: "SELECT shopping",
    data: [
      {
        Store: "Big Bazaar",
        City: "Mumbai",
        Revenue: 5200000,
        Expenses: 3100000,
        Customers: 45000,
        ProfitMargin: 22,
      },
      {
        Store: "Reliance Mart",
        City: "Delhi",
        Revenue: 6800000,
        Expenses: 4000000,
        Customers: 58000,
        ProfitMargin: 18,
      },
      {
        Store: "D-Mart",
        City: "Bangalore",
        Revenue: 5900000,
        Expenses: 3600000,
        Customers: 52000,
        ProfitMargin: 21,
      },
      {
        Store: "More",
        City: "Hyderabad",
        Revenue: 4700000,
        Expenses: 2900000,
        Customers: 40000,
        ProfitMargin: 24,
      },
      {
        Store: "Vishal Mega Mart",
        City: "Chennai",
        Revenue: 5300000,
        Expenses: 3100000,
        Customers: 47000,
        ProfitMargin: 19,
      },
      {
        Store: "Big Bazaar",
        City: "Kolkata",
        Revenue: 6200000,
        Expenses: 3700000,
        Customers: 54000,
        ProfitMargin: 20,
      },
      {
        Store: "D-Mart",
        City: "Pune",
        Revenue: 4900000,
        Expenses: 3000000,
        Customers: 43000,
        ProfitMargin: 22,
      },
      {
        Store: "Reliance Mart",
        City: "Ahmedabad",
        Revenue: 6500000,
        Expenses: 3900000,
        Customers: 60000,
        ProfitMargin: 17,
      },
      {
        Store: "More",
        City: "Jaipur",
        Revenue: 4600000,
        Expenses: 2800000,
        Customers: 41000,
        ProfitMargin: 23,
      },
      {
        Store: "Vishal Mega Mart",
        City: "Lucknow",
        Revenue: 5400000,
        Expenses: 3300000,
        Customers: 48000,
        ProfitMargin: 18,
      },
    ],
  },
];
